name: Electron CI

on:
  push:
    branches: [ release/vscode ]
  pull_request:

jobs:
  posix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - run: scripts/test-electron.sh
  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - run: .\scripts\test-electron.bat